version: "1"

services:
  comfyui:
    container_name: is-tools
    hostname: imagestacker-tools
    build: .
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - IS_LICENSE_KEY=desdes
    ports:
      - 3000:3000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./outputs:/outputs
      - ./data:/data